# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1800"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        exclude: ^third_party/
        args: ["--skip-string-normalization", "--line-length=119"]
        additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parenthese",
            "--line-width=119",
            "--ws",
            "--skip=third_party",
          ]
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        name: beautysh (bash)
        args: ["--indent-size=2", "--force-function-style=fnpar"]
  - repo: https://github.com/tuttlebr/nv-pre-commit
    rev: v0.0.5 # Use the ref you want to point at
    hooks:
      - id: detect-nv-keys
